<?php
/**
 * QuestionsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EUfunds GO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * QuestionsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class QuestionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getQuestionsApiQuestionsGet' => [
            'application/json',
        ],
        'rateQuestionApiRateQuestionPost' => [
            'application/json',
        ],
        'validateResponseApiQuestionResponsePost' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getQuestionsApiQuestionsGet
     *
     * Get Questions
     *
     * @param  int $project_id Project ID (required)
     * @param  QuestionDifficulty $difficulty Difficulty (optional)
     * @param  int $page Page number (optional, default to 0)
     * @param  int $page_size Page size (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuestionsApiQuestionsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function getQuestionsApiQuestionsGet($project_id, $difficulty = null, $page = 0, $page_size = 10, string $contentType = self::contentTypes['getQuestionsApiQuestionsGet'][0])
    {
        $this->getQuestionsApiQuestionsGetWithHttpInfo($project_id, $difficulty, $page, $page_size, $contentType);
    }

    /**
     * Operation getQuestionsApiQuestionsGetWithHttpInfo
     *
     * Get Questions
     *
     * @param  int $project_id Project ID (required)
     * @param  QuestionDifficulty $difficulty Difficulty (optional)
     * @param  int $page Page number (optional, default to 0)
     * @param  int $page_size Page size (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuestionsApiQuestionsGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function getQuestionsApiQuestionsGetWithHttpInfo($project_id, $difficulty = null, $page = 0, $page_size = 10, string $contentType = self::contentTypes['getQuestionsApiQuestionsGet'][0])
    {
        $request = $this->getQuestionsApiQuestionsGetRequest($project_id, $difficulty, $page, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getQuestionsApiQuestionsGetAsync
     *
     * Get Questions
     *
     * @param  int $project_id Project ID (required)
     * @param  QuestionDifficulty $difficulty Difficulty (optional)
     * @param  int $page Page number (optional, default to 0)
     * @param  int $page_size Page size (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuestionsApiQuestionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuestionsApiQuestionsGetAsync($project_id, $difficulty = null, $page = 0, $page_size = 10, string $contentType = self::contentTypes['getQuestionsApiQuestionsGet'][0])
    {
        return $this->getQuestionsApiQuestionsGetAsyncWithHttpInfo($project_id, $difficulty, $page, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getQuestionsApiQuestionsGetAsyncWithHttpInfo
     *
     * Get Questions
     *
     * @param  int $project_id Project ID (required)
     * @param  QuestionDifficulty $difficulty Difficulty (optional)
     * @param  int $page Page number (optional, default to 0)
     * @param  int $page_size Page size (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuestionsApiQuestionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getQuestionsApiQuestionsGetAsyncWithHttpInfo($project_id, $difficulty = null, $page = 0, $page_size = 10, string $contentType = self::contentTypes['getQuestionsApiQuestionsGet'][0])
    {
        $returnType = '';
        $request = $this->getQuestionsApiQuestionsGetRequest($project_id, $difficulty, $page, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getQuestionsApiQuestionsGet'
     *
     * @param  int $project_id Project ID (required)
     * @param  QuestionDifficulty $difficulty Difficulty (optional)
     * @param  int $page Page number (optional, default to 0)
     * @param  int $page_size Page size (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getQuestionsApiQuestionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getQuestionsApiQuestionsGetRequest($project_id, $difficulty = null, $page = 0, $page_size = 10, string $contentType = self::contentTypes['getQuestionsApiQuestionsGet'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling getQuestionsApiQuestionsGet'
            );
        }
        if ($project_id < 0) {
            throw new \InvalidArgumentException('invalid value for "$project_id" when calling QuestionsApi.getQuestionsApiQuestionsGet, must be bigger than or equal to 0.');
        }
        

        if ($page !== null && $page < 0) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling QuestionsApi.getQuestionsApiQuestionsGet, must be bigger than or equal to 0.');
        }
        
        if ($page_size !== null && $page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling QuestionsApi.getQuestionsApiQuestionsGet, must be smaller than or equal to 100.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling QuestionsApi.getQuestionsApiQuestionsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/api/questions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $project_id,
            'project_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $difficulty,
            'difficulty', // param base name
            'QuestionDifficulty', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation rateQuestionApiRateQuestionPost
     *
     * Rate Question
     *
     * @param  \OpenAPI\Client\Model\RateQuestionRequest $rate_question_request rate_question_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rateQuestionApiRateQuestionPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function rateQuestionApiRateQuestionPost($rate_question_request, string $contentType = self::contentTypes['rateQuestionApiRateQuestionPost'][0])
    {
        $this->rateQuestionApiRateQuestionPostWithHttpInfo($rate_question_request, $contentType);
    }

    /**
     * Operation rateQuestionApiRateQuestionPostWithHttpInfo
     *
     * Rate Question
     *
     * @param  \OpenAPI\Client\Model\RateQuestionRequest $rate_question_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rateQuestionApiRateQuestionPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function rateQuestionApiRateQuestionPostWithHttpInfo($rate_question_request, string $contentType = self::contentTypes['rateQuestionApiRateQuestionPost'][0])
    {
        $request = $this->rateQuestionApiRateQuestionPostRequest($rate_question_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation rateQuestionApiRateQuestionPostAsync
     *
     * Rate Question
     *
     * @param  \OpenAPI\Client\Model\RateQuestionRequest $rate_question_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rateQuestionApiRateQuestionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rateQuestionApiRateQuestionPostAsync($rate_question_request, string $contentType = self::contentTypes['rateQuestionApiRateQuestionPost'][0])
    {
        return $this->rateQuestionApiRateQuestionPostAsyncWithHttpInfo($rate_question_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation rateQuestionApiRateQuestionPostAsyncWithHttpInfo
     *
     * Rate Question
     *
     * @param  \OpenAPI\Client\Model\RateQuestionRequest $rate_question_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rateQuestionApiRateQuestionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rateQuestionApiRateQuestionPostAsyncWithHttpInfo($rate_question_request, string $contentType = self::contentTypes['rateQuestionApiRateQuestionPost'][0])
    {
        $returnType = '';
        $request = $this->rateQuestionApiRateQuestionPostRequest($rate_question_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'rateQuestionApiRateQuestionPost'
     *
     * @param  \OpenAPI\Client\Model\RateQuestionRequest $rate_question_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rateQuestionApiRateQuestionPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function rateQuestionApiRateQuestionPostRequest($rate_question_request, string $contentType = self::contentTypes['rateQuestionApiRateQuestionPost'][0])
    {

        // verify the required parameter 'rate_question_request' is set
        if ($rate_question_request === null || (is_array($rate_question_request) && count($rate_question_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rate_question_request when calling rateQuestionApiRateQuestionPost'
            );
        }


        $resourcePath = '/api/rate-question';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($rate_question_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($rate_question_request));
            } else {
                $httpBody = $rate_question_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateResponseApiQuestionResponsePost
     *
     * Validate Response
     *
     * @param  \OpenAPI\Client\Model\QuestionResponseRequest $question_response_request question_response_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateResponseApiQuestionResponsePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function validateResponseApiQuestionResponsePost($question_response_request, string $contentType = self::contentTypes['validateResponseApiQuestionResponsePost'][0])
    {
        $this->validateResponseApiQuestionResponsePostWithHttpInfo($question_response_request, $contentType);
    }

    /**
     * Operation validateResponseApiQuestionResponsePostWithHttpInfo
     *
     * Validate Response
     *
     * @param  \OpenAPI\Client\Model\QuestionResponseRequest $question_response_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateResponseApiQuestionResponsePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateResponseApiQuestionResponsePostWithHttpInfo($question_response_request, string $contentType = self::contentTypes['validateResponseApiQuestionResponsePost'][0])
    {
        $request = $this->validateResponseApiQuestionResponsePostRequest($question_response_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation validateResponseApiQuestionResponsePostAsync
     *
     * Validate Response
     *
     * @param  \OpenAPI\Client\Model\QuestionResponseRequest $question_response_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateResponseApiQuestionResponsePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateResponseApiQuestionResponsePostAsync($question_response_request, string $contentType = self::contentTypes['validateResponseApiQuestionResponsePost'][0])
    {
        return $this->validateResponseApiQuestionResponsePostAsyncWithHttpInfo($question_response_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateResponseApiQuestionResponsePostAsyncWithHttpInfo
     *
     * Validate Response
     *
     * @param  \OpenAPI\Client\Model\QuestionResponseRequest $question_response_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateResponseApiQuestionResponsePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateResponseApiQuestionResponsePostAsyncWithHttpInfo($question_response_request, string $contentType = self::contentTypes['validateResponseApiQuestionResponsePost'][0])
    {
        $returnType = '';
        $request = $this->validateResponseApiQuestionResponsePostRequest($question_response_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateResponseApiQuestionResponsePost'
     *
     * @param  \OpenAPI\Client\Model\QuestionResponseRequest $question_response_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['validateResponseApiQuestionResponsePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function validateResponseApiQuestionResponsePostRequest($question_response_request, string $contentType = self::contentTypes['validateResponseApiQuestionResponsePost'][0])
    {

        // verify the required parameter 'question_response_request' is set
        if ($question_response_request === null || (is_array($question_response_request) && count($question_response_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $question_response_request when calling validateResponseApiQuestionResponsePost'
            );
        }


        $resourcePath = '/api/question-response';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($question_response_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($question_response_request));
            } else {
                $httpBody = $question_response_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
