<?php
/**
 * ProjectCategory
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * EUfunds GO
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProjectCategory Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectCategory
{
    /**
     * Possible values of this enum
     */
    public const TURYSTYKA = 'Turystyka';

    public const REWITALIZACJA = 'Rewitalizacja';

    public const OCHRONA_RODOWISKA = 'Ochrona środowiska';

    public const WSPPRACA_MIDZYNARODOWA = 'Współpraca międzynarodowa';

    public const BADANIA_ROZWJ_INNOWACJE = 'Badania, rozwój, innowacje';

    public const KULTURA_I_SZTUKA = 'Kultura i sztuka';

    public const NAUKA_I_EDUKACJA = 'Nauka i edukacja';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TURYSTYKA,
            self::REWITALIZACJA,
            self::OCHRONA_RODOWISKA,
            self::WSPPRACA_MIDZYNARODOWA,
            self::BADANIA_ROZWJ_INNOWACJE,
            self::KULTURA_I_SZTUKA,
            self::NAUKA_I_EDUKACJA
        ];
    }
}


